name: panGPT
channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_gnu
- absl-py=2.1.0=pyhd8ed1ab_0
- aiohttp=3.9.5=py311h459d7ec_0
- aiosignal=1.3.1=pyhd8ed1ab_0
- alsa-lib=1.2.13=hb9d3cd8_0
- anndata=0.11.4=pyhd8ed1ab_0
- appdirs=1.4.4=pyh9f0ad1d_0
- arpack=3.9.1=nompi_hf03ea27_102
- array-api-compat=1.12.0=pyhe01879c_0
- astunparse=1.6.3=pyhd8ed1ab_2
- attrs=23.2.0=pyh71513ae_0
- aws-c-auth=0.7.31=hcdce11a_5
- aws-c-cal=0.7.4=hd3f4568_4
- aws-c-common=0.9.31=hb9d3cd8_0
- aws-c-compression=0.2.19=hf20e7d7_4
- aws-c-event-stream=0.5.0=h72d8268_0
- aws-c-http=0.8.10=h6bb76cc_5
- aws-c-io=0.14.20=h389d861_2
- aws-c-mqtt=0.10.7=had056f2_5
- aws-c-s3=0.7.0=hc85afc5_0
- aws-c-sdkutils=0.1.19=hf20e7d7_6
- aws-checksums=0.1.20=hf20e7d7_3
- aws-crt-cpp=0.29.0=h07ed512_0
- aws-sdk-cpp=1.11.407=h9c41b47_6
- azure-core-cpp=1.14.0=h5cfcd09_0
- azure-identity-cpp=1.10.0=h113e628_0
- azure-storage-blobs-cpp=12.13.0=h3cf044e_1
- azure-storage-common-cpp=12.8.0=h736e048_1
- azure-storage-files-datalake-cpp=12.12.0=ha633028_1
- brotli=1.1.0=hd590300_1
- brotli-bin=1.1.0=hd590300_1
- brotli-python=1.1.0=py311hb755f60_1
- bzip2=1.0.8=hd590300_5
- c-ares=1.34.2=heb4867d_0
- ca-certificates=2024.8.30=hbcca054_0
- cached-property=1.5.2=hd8ed1ab_1
- cached_property=1.5.2=pyha770c72_1
- cairo=1.18.0=hebfffa5_3
- certifi=2024.8.30=pyhd8ed1ab_0
- cffi=1.16.0=py311hb3a22ac_0
- charset-normalizer=3.3.2=pyhd8ed1ab_0
- click=8.1.7=unix_pyh707e725_0
- cloudpickle=3.1.0=pyhd8ed1ab_1
- colorama=0.4.6=pyhd8ed1ab_0
- contourpy=1.3.1=py311hd18a35c_0
- cycler=0.12.1=pyhd8ed1ab_1
- cyrus-sasl=2.1.27=h54b06d7_7
- datasets=2.20.0=pyhd8ed1ab_0
- dbus=1.13.6=h5008d03_3
- dill=0.3.8=pyhd8ed1ab_0
- docker-pycreds=0.4.0=py_0
- double-conversion=3.3.1=h5888daf_0
- exceptiongroup=1.3.1=pyhd8ed1ab_0
- expat=2.6.2=h59595ed_0
- filelock=3.15.4=pyhd8ed1ab_0
- flatbuffers=24.3.25=h59595ed_0
- font-ttf-dejavu-sans-mono=2.37=hab24e00_0
- font-ttf-inconsolata=3.000=h77eed37_0
- font-ttf-source-code-pro=2.038=h77eed37_0
- font-ttf-ubuntu=0.83=h77eed37_3
- fontconfig=2.14.2=h14ed4e7_0
- fonts-conda-ecosystem=1=0
- fonts-conda-forge=1=0
- fonttools=4.56.0=py311h2dc5d0c_0
- freetype=2.12.1=h267a509_2
- frozenlist=1.4.1=py311h459d7ec_0
- fsspec=2024.5.0=pyhff2d567_0
- gast=0.5.5=pyhd8ed1ab_0
- gflags=2.2.2=he1b5a44_1004
- giflib=5.2.2=hd590300_0
- gitdb=4.0.11=pyhd8ed1ab_0
- gitpython=3.1.43=pyhd8ed1ab_0
- glog=0.7.1=hbabe93e_0
- glpk=5.0=h445213a_0
- gmp=6.3.0=hac33072_2
- google-pasta=0.2.0=pyhd8ed1ab_1
- graphite2=1.3.13=h59595ed_1003
- grpcio=1.65.5=py311h9c9ff8c_0
- h2=4.1.0=pyhd8ed1ab_0
- h5py=3.12.1=nompi_py311hb639ac4_102
- harfbuzz=9.0.0=hda332d3_1
- hdf5=1.14.3=nompi_hdf9ad27_105
- hpack=4.0.0=pyh9f0ad1d_0
- huggingface_hub=0.23.4=pyhd8ed1ab_0
- hyperframe=6.0.1=pyhd8ed1ab_0
- icu=75.1=he02047a_0
- idna=3.7=pyhd8ed1ab_0
- igraph=1.0.1=hfe3e89f_0
- importlib-metadata=8.0.0=pyha770c72_0
- joblib=1.4.2=pyhd8ed1ab_0
- keras=3.6.0=pyhd8ed1ab_0
- keyutils=1.6.1=h166bdaf_0
- kiwisolver=1.4.7=py311hd18a35c_0
- krb5=1.21.3=h659f571_0
- lcms2=2.17=h717163a_0
- ld_impl_linux-64=2.40=hf3520f5_7
- legacy-api-wrap=1.5=pyhd8ed1ab_0
- lerc=4.0.0=h27087fc_0
- libabseil=20240722.0=cxx17_h5888daf_1
- libaec=1.1.3=h59595ed_0
- libarrow=16.1.0=ha5db6c2_36_cpu
- libarrow-acero=16.1.0=h5888daf_36_cpu
- libarrow-dataset=16.1.0=h5888daf_36_cpu
- libarrow-substrait=16.1.0=he882d9a_36_cpu
- libblas=3.9.0=22_linux64_openblas
- libbrotlicommon=1.1.0=hd590300_1
- libbrotlidec=1.1.0=hd590300_1
- libbrotlienc=1.1.0=hd590300_1
- libcblas=3.9.0=22_linux64_openblas
- libclang-cpp19.1=19.1.2=default_hb5137d0_1
- libclang13=19.1.2=default_h9c6a7e4_1
- libcrc32c=1.1.2=h9c3ff4c_0
- libcups=2.3.3=h4637d8d_4
- libcurl=8.10.1=hbbe4b11_0
- libdeflate=1.23=h4ddbbb0_0
- libdrm=2.4.124=hb9d3cd8_0
- libedit=3.1.20191231=he28a2e2_2
- libegl=1.7.0=ha4b6fd6_2
- libev=4.33=hd590300_2
- libevent=2.1.12=hf998b51_1
- libexpat=2.6.2=h59595ed_0
- libffi=3.4.2=h7f98852_5
- libgcc=14.2.0=h77fa898_1
- libgcc-ng=14.2.0=h69a702a_1
- libgfortran=3.0.0=1
- libgfortran-ng=14.1.0=h69a702a_0
- libgfortran5=14.1.0=hc5f4f2c_0
- libgl=1.7.0=ha4b6fd6_2
- libglib=2.82.2=h2ff4ddf_1
- libglvnd=1.7.0=ha4b6fd6_2
- libglx=1.7.0=ha4b6fd6_2
- libgomp=14.2.0=h77fa898_1
- libgoogle-cloud=2.30.0=h438788a_0
- libgoogle-cloud-storage=2.30.0=h0121fbd_0
- libgrpc=1.65.5=hf5c653b_0
- libhwloc=2.11.2=default_he43201b_1000
- libiconv=1.18=h3b78370_2
- libjpeg-turbo=3.0.0=hd590300_1
- liblapack=3.9.0=22_linux64_openblas
- libllvm14=14.0.6=hcd5def8_4
- libllvm19=19.1.2=ha7bfdaf_0
- liblzma=5.8.1=hb9d3cd8_2
- liblzma-devel=5.8.1=hb9d3cd8_2
- libnghttp2=1.58.0=h47da74e_1
- libnsl=2.0.1=hd590300_0
- libntlm=1.8=hb9d3cd8_0
- libopenblas=0.3.27=pthreads_hac2b453_1
- libopengl=1.7.0=ha4b6fd6_2
- libparquet=16.1.0=h6bd9018_36_cpu
- libpciaccess=0.18=hd590300_0
- libpng=1.6.44=hadc24fc_0
- libpq=17.0=h04577a9_4
- libprotobuf=5.27.5=h5b01275_2
- libre2-11=2024.07.02=hbbce691_1
- libsqlite=3.47.0=hadc24fc_0
- libssh2=1.11.0=h0841786_0
- libstdcxx=14.2.0=hc0a3c3a_1
- libstdcxx-ng=14.2.0=h4852527_1
- libthrift=0.21.0=h0e7cc3e_0
- libtiff=4.7.0=hd9ff511_3
- libutf8proc=2.8.0=h166bdaf_0
- libuuid=2.38.1=h0b41bf4_0
- libwebp-base=1.5.0=h851e524_0
- libxcb=1.17.0=h8a09558_0
- libxcrypt=4.4.36=hd590300_1
- libxkbcommon=1.7.0=h2c5496b_1
- libxml2=2.15.1=h26afc86_0
- libxml2-16=2.15.1=ha9997c6_0
- libxml2-devel=2.15.1=h26afc86_0
- libxslt=1.1.43=h711ed8c_1
- libzlib=1.3.1=h4ab18f5_1
- llvmlite=0.43.0=py311h9c9ff8c_1
- lz4-c=1.9.4=hcb278e6_0
- markdown=3.6=pyhd8ed1ab_0
- markdown-it-py=3.0.0=pyhd8ed1ab_0
- markupsafe=2.1.5=py311h459d7ec_0
- matplotlib=3.10.1=py311h38be061_0
- matplotlib-base=3.10.1=py311h2b939e6_0
- mdurl=0.1.2=pyhd8ed1ab_0
- multidict=6.0.5=py311h459d7ec_0
- multiprocess=0.70.16=py311h459d7ec_0
- munkres=1.1.4=pyh9f0ad1d_0
- mysql-common=9.0.1=h266115a_2
- mysql-libs=9.0.1=he0572af_2
- namex=0.0.8=pyhd8ed1ab_0
- natsort=8.4.0=pyh29332c3_1
- ncurses=6.5=h59595ed_0
- networkx=3.6.1=pyhcf101f3_0
- numba=0.60.0=py311h4bc866e_0
- numpy=1.26.4=py311h64a7726_0
- openjpeg=2.5.3=h5fbd93e_0
- openldap=2.6.8=hedd0468_0
- openssl=3.3.2=hb9d3cd8_0
- opt_einsum=3.4.0=pyhd8ed1ab_0
- optree=0.13.0=py311hd18a35c_0
- orc=2.0.2=h690cf93_1
- packaging=24.1=pyhd8ed1ab_0
- pandas=2.2.2=py311h14de704_1
- pathtools=0.1.2=py_1
- patsy=1.0.1=pyhd8ed1ab_1
- pcre2=10.44=hba22ea6_2
- pillow=11.1.0=py311h1322bbf_0
- pip=24.0=pyhd8ed1ab_0
- pixman=0.44.2=h29eaf8c_0
- promise=2.3=py311h38be061_9
- psutil=6.0.0=py311h331c9d8_0
- pthread-stubs=0.4=hb9d3cd8_1002
- pyarrow=16.1.0=py311hbd00459_4
- pyarrow-core=16.1.0=py311h8c3dac4_4_cpu
- pyarrow-hotfix=0.6=pyhd8ed1ab_0
- pycparser=2.22=pyhd8ed1ab_0
- pygments=2.18.0=pyhd8ed1ab_0
- pynndescent=0.5.13=pyhd8ed1ab_1
- pyparsing=3.2.1=pyhd8ed1ab_0
- pyside6=6.8.0.2=py311h9053184_0
- pysocks=1.7.1=pyha2e5f31_6
- python=3.11.9=hb806964_0_cpython
- python-dateutil=2.9.0=pyhd8ed1ab_0
- python-flatbuffers=24.3.25=pyh59ac667_0
- python-igraph=1.0.0=py311h1ddb823_0
- python-tzdata=2024.1=pyhd8ed1ab_0
- python-xxhash=3.4.1=py311h459d7ec_0
- python_abi=3.11=4_cp311
- pytz=2024.1=pyhd8ed1ab_0
- pyyaml=6.0.1=py311h459d7ec_1
- qhull=2020.2=h434a139_5
- qt6-main=6.8.0=h6e8976b_0
- re2=2024.07.02=h77b4e00_1
- readline=8.2=h8228510_1
- regex=2024.5.15=py311h331c9d8_0
- requests=2.32.3=pyhd8ed1ab_0
- rich=13.9.3=pyhd8ed1ab_0
- s2n=1.5.5=h3931f03_0
- safetensors=0.4.3=py311h46250e7_0
- scanpy=1.11.5=pyhd8ed1ab_0
- scikit-learn=1.5.1=py311hd632256_0
- scipy=1.14.0=py311h517d4fd_1
- seaborn=0.13.2=hd8ed1ab_3
- seaborn-base=0.13.2=pyhd8ed1ab_3
- sentry-sdk=2.9.0=pyhd8ed1ab_0
- session-info2=0.2.3=pyhd8ed1ab_0
- setproctitle=1.3.3=py311h459d7ec_0
- setuptools=70.2.0=pyhd8ed1ab_0
- shortuuid=1.0.13=pyhd8ed1ab_0
- six=1.16.0=pyh6c4a22f_0
- slicer=0.0.8=pyhd8ed1ab_0
- smmap=5.0.0=pyhd8ed1ab_0
- snappy=1.2.1=ha2e4443_0
- statsmodels=0.14.6=py311h0372a8f_0
- tbb=2022.0.0=hceb3a55_0
- tensorboard-data-server=0.7.0=py311h63ff55d_1
- tensorflow=2.17.0=cpu_py311h6ac8430_3
- tensorflow-estimator=2.17.0=cpu_py311h331965b_3
- termcolor=2.5.0=pyhd8ed1ab_0
- texttable=1.7.0=pyhd8ed1ab_1
- tf-keras=2.17.0=pyhd8ed1ab_0
- threadpoolctl=3.5.0=pyhc1e730c_0
- tiktoken=0.7.0=py311h339c092_0
- tk=8.6.13=noxft_h4845f30_101
- tokenizers=0.19.1=py311h6640629_0
- tornado=6.4.2=py311h9ecbd09_0
- tqdm=4.66.4=pyhd8ed1ab_0
- transformers=4.42.3=pyhd8ed1ab_0
- typing-extensions=4.12.2=hd8ed1ab_0
- typing_extensions=4.12.2=pyha770c72_0
- tzdata=2024a=h0c530f3_0
- umap-learn=0.5.7=py311h38be061_1
- unicodedata2=16.0.0=py311h9ecbd09_0
- urllib3=2.2.2=pyhd8ed1ab_1
- wandb=0.13.1=pyhd8ed1ab_0
- wayland=1.23.1=h3e06ad9_0
- werkzeug=3.0.3=pyhd8ed1ab_0
- wheel=0.43.0=pyhd8ed1ab_1
- wrapt=1.16.0=py311h9ecbd09_1
- xcb-util=0.4.1=hb711507_2
- xcb-util-cursor=0.1.5=hb9d3cd8_0
- xcb-util-image=0.4.0=hb711507_2
- xcb-util-keysyms=0.4.1=hb711507_0
- xcb-util-renderutil=0.3.10=hb711507_0
- xcb-util-wm=0.4.2=hb711507_0
- xkeyboard-config=2.43=hb9d3cd8_0
- xorg-libice=1.1.2=hb9d3cd8_0
- xorg-libsm=1.2.5=he73a12e_0
- xorg-libx11=1.8.11=h4f16b4b_0
- xorg-libxau=1.0.12=hb9d3cd8_0
- xorg-libxcomposite=0.4.6=hb9d3cd8_2
- xorg-libxcursor=1.2.3=hb9d3cd8_0
- xorg-libxdamage=1.1.6=hb9d3cd8_0
- xorg-libxdmcp=1.1.5=hb9d3cd8_0
- xorg-libxext=1.3.6=hb9d3cd8_0
- xorg-libxfixes=6.0.1=hb9d3cd8_0
- xorg-libxi=1.8.2=hb9d3cd8_0
- xorg-libxrandr=1.5.4=hb9d3cd8_0
- xorg-libxrender=0.9.12=hb9d3cd8_0
- xorg-libxtst=1.2.5=hb9d3cd8_3
- xorg-libxxf86vm=1.1.6=hb9d3cd8_0
- xxhash=0.8.2=hd590300_0
- xz=5.8.1=hbcc6ac9_2
- xz-gpl-tools=5.8.1=hbcc6ac9_2
- xz-tools=5.8.1=hb9d3cd8_2
- yaml=0.2.5=h7f98852_2
- yarl=1.9.4=py311h459d7ec_0
- zipp=3.19.2=pyhd8ed1ab_0
- zlib=1.3.1=h4ab18f5_1
- zstandard=0.22.0=py311hb6f056b_1
- zstd=1.5.6=ha6fb4c9_0

